In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as mp
import os

In [2]:
image=cv2.imread("360_F_293553751_Rq6Vv4LuPJjoYTaLgGC3Czh6TKJp6BoN.jpg")
image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)

In [3]:
pixels=image.reshape((-1,3))
pixels=np.float32(pixels)
print(pixels)

[[ 1. 40. 83.]
 [ 1. 40. 83.]
 [ 1. 40. 83.]
 ...
 [ 3. 88.  0.]
 [ 8. 69.  0.]
 [ 0. 39.  0.]]


In [4]:
k=8

In [5]:
when_stop=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,100,0.2)

In [6]:
Error,labels,centers=cv2.kmeans(pixels,k,None,when_stop,10,cv2.KMEANS_RANDOM_CENTERS)

In [7]:
centers=np.uint8(centers)

In [8]:
compressed=centers[labels.flatten()]


In [9]:
compressed=compressed.reshape(image.shape)